/* Purpose: the settings a program embedding the engine applies before the
 *   engine loads, as C constants, so the C seat boots under the bounds the
 *   Python seat declares rather than numbers of its own.
 * Assumes: each block below is one Setting in
 *   extensions/python/metta/_catalog/bounds.py that names the SWI flag it
 *   sets.
 * Guarantees:
 *   - this file is GENERATED by extensions/python/tools/boundsgen.py from
 *     those declarations, beside Config.configure's signature and the
 *     settings table in DEVELOPING.md; edit the declaration and rerun the
 *     tool with --write, never this file, and the tool's check fails on any
 *     drift [tested: test_each_declaration_projection_refuses_an_independent_edit;
 *     commit=WORKTREE]
 *   - for a setting <name>, MT_<NAME>_FLAG is the SWI flag it sets,
 *     MT_<NAME>_ENVIRONMENT the environment variable whose value replaces its
 *     default, present when the declaration names one, and MT_<NAME>_DEFAULT
 *     the default in the flag's own unit [tested:
 *     test_setting_declaration_reaches_every_projection; commit=WORKTREE]
 * Open Obligations: None.
 */
#ifndef CMETTA_SETTINGS_H
#define CMETTA_SETTINGS_H

/* stack_limit: Maximum SWI stack size in bytes. */
#define MT_STACK_LIMIT_FLAG "stack_limit"
#define MT_STACK_LIMIT_ENVIRONMENT "METTA_STACK_LIMIT"
#define MT_STACK_LIMIT_DEFAULT 8000000000ULL

#endif
