/* Purpose: the engine's own closed value sets as C enums, one per
 *   (vocabulary ...) row in &metta, so a C program names a member exactly and
 *   a misspelt member fails to compile where a misspelt word would answer
 *   nothing.
 * Assumes: each block below is one (vocabulary ...) row in the &metta
 *   catalog, whose presets live in engine/spaces/catalog.pl.
 * Guarantees:
 *   - this file is GENERATED by extensions/python/tools/vocabgen.py from the
 *     engine's own rows, beside the Python module and the Node table the same
 *     tool writes; edit the presets in engine/spaces/catalog.pl and rerun it
 *     with --write, never this file, and the vocab-sync lane fails on any
 *     drift [tested: test_the_vocabulary_module_is_generated,
 *     test_vocabulary_wrong_spelling_is_refused_independently;
 *     commit=b88f5049744930e5bc04be5c556c69fa27e371ad]
 *   - each enum holds its row's members in the catalog's own order, so a
 *     member's value is its position in the row, which for mt_effect_class
 *     is its rank, and mt_<vocabulary>_names[] holds the engine's word for
 *     the member at that position, as the running engine's rows read
 *     [tested: extensions/cmetta/tests/test_cmetta.c,
 *     test_the_generated_vocabularies_are_the_engines;
 *     commit=4d9802e2380b906f3919dfb77ad8ff7c3adc5c7f]
 *   - a C name is C's casing of the engine's words and never a new name: the
 *     enum's tag is mt_ and the words of the vocabulary's MeTTa type name in
 *     lower case joined by underscores, and a member is MT_ and the type's
 *     words then the member's in upper case, so pureStructural in EffectClass
 *     is MT_EFFECT_CLASS_PURE_STRUCTURAL in enum mt_effect_class and
 *     best-first in AnswerPolicy is MT_ANSWER_POLICY_BEST_FIRST
 *   - each type is an enum tag with no typedef, so it lives in C's tag
 *     namespace, apart from the functions and typedefs of cmetta.h: the limit
 *     vocabulary's enum mt_limit and the door mt_limit are two names
 *   - mt_<vocabulary>_of(word, &member) answers whether word is a member and
 *     writes *member only when it is, so no word reads as a default member
 *     [tested: extensions/cmetta/tests/test_cmetta.c,
 *     test_the_generated_vocabularies_are_the_engines;
 *     commit=4d9802e2380b906f3919dfb77ad8ff7c3adc5c7f]
 *   - a vocabulary the engine declares OPEN also admits a word registered
 *     through (add-atom &metta (vocabulary-member <vocabulary> <word>)): its
 *     enum holds the words the engine ships, and its lookup answers false for
 *     a registered word as for any word the enum does not hold, which a C
 *     program passes on as text
 *   - mt_vocabularies[] holds every vocabulary under the engine's own name
 *     with its words, the reflection door for a tool that enumerates them
 * Open Obligations: None.
 */
#ifndef CMETTA_VOCABULARIES_H
#define CMETTA_VOCABULARIES_H

#include <stdbool.h>
#include <stddef.h>
#include <string.h>

/* A table is static, so a translation unit that names none of them holds
   each unused, which -Wunused-const-variable reports and -Wall enables for C;
   GCC and Clang are told they may go unused. */
#if defined(__GNUC__) || defined(__clang__)
#define MT_VOCABULARY_TABLE __attribute__((unused)) static const
#else
#define MT_VOCABULARY_TABLE static const
#endif

/* How many words a vocabulary's table holds. */
#define MT_VOCABULARY_COUNT(table) (sizeof (table) / sizeof *(table))

/* The position of word among a vocabulary's words, written to *index, or
   false when none of them is word. Time: count string comparisons. */
static inline bool mt_vocabulary_index(const char *const *words, size_t count,
                                       const char *word, size_t *index)
{ if ( !word )
    return false;
  for (size_t i = 0; i < count; i++)
  { if ( strcmp(words[i], word) == 0 )
    { *index = i;
      return true;
    }
  }
  return false;
}

/* One vocabulary: the engine's name for it, and its words in member order. */
typedef struct mt_vocabulary
{ const char        *name;
  const char *const *words;
  size_t             count;
} mt_vocabulary;

/* (vocabulary ClauseFailedEnum ClauseFailNonDet ClauseFailDet) */
enum mt_clause_failed_enum {
  MT_CLAUSE_FAILED_ENUM_CLAUSE_FAIL_NON_DET,
  MT_CLAUSE_FAILED_ENUM_CLAUSE_FAIL_DET,
};

/* The engine's word for each enum mt_clause_failed_enum member, by position. */
MT_VOCABULARY_TABLE char *const mt_clause_failed_enum_names[] = {
  "ClauseFailNonDet",
  "ClauseFailDet",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_clause_failed_enum_of(const char *word, enum mt_clause_failed_enum *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_clause_failed_enum_names,
                            MT_VOCABULARY_COUNT(mt_clause_failed_enum_names), word, &i) )
    return false;
  *member = (enum mt_clause_failed_enum)i;
  return true;
}

/* (vocabulary EvaluationOrderEnum OrderClause OrderFittest) */
enum mt_evaluation_order_enum {
  MT_EVALUATION_ORDER_ENUM_ORDER_CLAUSE,
  MT_EVALUATION_ORDER_ENUM_ORDER_FITTEST,
};

/* The engine's word for each enum mt_evaluation_order_enum member, by position. */
MT_VOCABULARY_TABLE char *const mt_evaluation_order_enum_names[] = {
  "OrderClause",
  "OrderFittest",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_evaluation_order_enum_of(const char *word, enum mt_evaluation_order_enum *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_evaluation_order_enum_names,
                            MT_VOCABULARY_COUNT(mt_evaluation_order_enum_names), word, &i) )
    return false;
  *member = (enum mt_evaluation_order_enum)i;
  return true;
}

/* (vocabulary FunctionResultEnum Nondeterministic Deterministic) */
enum mt_function_result_enum {
  MT_FUNCTION_RESULT_ENUM_NONDETERMINISTIC,
  MT_FUNCTION_RESULT_ENUM_DETERMINISTIC,
};

/* The engine's word for each enum mt_function_result_enum member, by position. */
MT_VOCABULARY_TABLE char *const mt_function_result_enum_names[] = {
  "Nondeterministic",
  "Deterministic",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_function_result_enum_of(const char *word, enum mt_function_result_enum *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_function_result_enum_names,
                            MT_VOCABULARY_COUNT(mt_function_result_enum_names), word, &i) )
    return false;
  *member = (enum mt_function_result_enum)i;
  return true;
}

/* (vocabulary MismatchEnum MismatchOriginal MismatchError MismatchFail) */
enum mt_mismatch_enum {
  MT_MISMATCH_ENUM_MISMATCH_ORIGINAL,
  MT_MISMATCH_ENUM_MISMATCH_ERROR,
  MT_MISMATCH_ENUM_MISMATCH_FAIL,
};

/* The engine's word for each enum mt_mismatch_enum member, by position. */
MT_VOCABULARY_TABLE char *const mt_mismatch_enum_names[] = {
  "MismatchOriginal",
  "MismatchError",
  "MismatchFail",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_mismatch_enum_of(const char *word, enum mt_mismatch_enum *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_mismatch_enum_names,
                            MT_VOCABULARY_COUNT(mt_mismatch_enum_names), word, &i) )
    return false;
  *member = (enum mt_mismatch_enum)i;
  return true;
}

/* (vocabulary NoMatchEnum NoMatchOriginal NoMatchFail NoMatchError) */
enum mt_no_match_enum {
  MT_NO_MATCH_ENUM_NO_MATCH_ORIGINAL,
  MT_NO_MATCH_ENUM_NO_MATCH_FAIL,
  MT_NO_MATCH_ENUM_NO_MATCH_ERROR,
};

/* The engine's word for each enum mt_no_match_enum member, by position. */
MT_VOCABULARY_TABLE char *const mt_no_match_enum_names[] = {
  "NoMatchOriginal",
  "NoMatchFail",
  "NoMatchError",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_no_match_enum_of(const char *word, enum mt_no_match_enum *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_no_match_enum_names,
                            MT_VOCABULARY_COUNT(mt_no_match_enum_names), word, &i) )
    return false;
  *member = (enum mt_no_match_enum)i;
  return true;
}

/* (vocabulary OutOfClausesEnum FailureOriginal FailureEmpty FailureError) */
enum mt_out_of_clauses_enum {
  MT_OUT_OF_CLAUSES_ENUM_FAILURE_ORIGINAL,
  MT_OUT_OF_CLAUSES_ENUM_FAILURE_EMPTY,
  MT_OUT_OF_CLAUSES_ENUM_FAILURE_ERROR,
};

/* The engine's word for each enum mt_out_of_clauses_enum member, by position. */
MT_VOCABULARY_TABLE char *const mt_out_of_clauses_enum_names[] = {
  "FailureOriginal",
  "FailureEmpty",
  "FailureError",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_out_of_clauses_enum_of(const char *word, enum mt_out_of_clauses_enum *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_out_of_clauses_enum_names,
                            MT_VOCABULARY_COUNT(mt_out_of_clauses_enum_names), word, &i) )
    return false;
  *member = (enum mt_out_of_clauses_enum)i;
  return true;
}

/* (vocabulary agenda-policy declaration recency specificity priority user) */
enum mt_agenda_policy {
  MT_AGENDA_POLICY_DECLARATION,
  MT_AGENDA_POLICY_RECENCY,
  MT_AGENDA_POLICY_SPECIFICITY,
  MT_AGENDA_POLICY_PRIORITY,
  MT_AGENDA_POLICY_USER,
};

/* The engine's word for each enum mt_agenda_policy member, by position. */
MT_VOCABULARY_TABLE char *const mt_agenda_policy_names[] = {
  "declaration",
  "recency",
  "specificity",
  "priority",
  "user",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_agenda_policy_of(const char *word, enum mt_agenda_policy *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_agenda_policy_names,
                            MT_VOCABULARY_COUNT(mt_agenda_policy_names), word, &i) )
    return false;
  *member = (enum mt_agenda_policy)i;
  return true;
}

/* (vocabulary algebra-law combine-associative combine-commutative extend-
   associative extend-commutative left-distributive right-distributive
   combine-idempotent combine-zero-identity extend-one-identity extend-zero-
   annihilates contraction roundtrip equivalent associative commutative
   distributive idempotent identity distributes-over) */
enum mt_algebra_law {
  MT_ALGEBRA_LAW_COMBINE_ASSOCIATIVE,
  MT_ALGEBRA_LAW_COMBINE_COMMUTATIVE,
  MT_ALGEBRA_LAW_EXTEND_ASSOCIATIVE,
  MT_ALGEBRA_LAW_EXTEND_COMMUTATIVE,
  MT_ALGEBRA_LAW_LEFT_DISTRIBUTIVE,
  MT_ALGEBRA_LAW_RIGHT_DISTRIBUTIVE,
  MT_ALGEBRA_LAW_COMBINE_IDEMPOTENT,
  MT_ALGEBRA_LAW_COMBINE_ZERO_IDENTITY,
  MT_ALGEBRA_LAW_EXTEND_ONE_IDENTITY,
  MT_ALGEBRA_LAW_EXTEND_ZERO_ANNIHILATES,
  MT_ALGEBRA_LAW_CONTRACTION,
  MT_ALGEBRA_LAW_ROUNDTRIP,
  MT_ALGEBRA_LAW_EQUIVALENT,
  MT_ALGEBRA_LAW_ASSOCIATIVE,
  MT_ALGEBRA_LAW_COMMUTATIVE,
  MT_ALGEBRA_LAW_DISTRIBUTIVE,
  MT_ALGEBRA_LAW_IDEMPOTENT,
  MT_ALGEBRA_LAW_IDENTITY,
  MT_ALGEBRA_LAW_DISTRIBUTES_OVER,
};

/* The engine's word for each enum mt_algebra_law member, by position. */
MT_VOCABULARY_TABLE char *const mt_algebra_law_names[] = {
  "combine-associative",
  "combine-commutative",
  "extend-associative",
  "extend-commutative",
  "left-distributive",
  "right-distributive",
  "combine-idempotent",
  "combine-zero-identity",
  "extend-one-identity",
  "extend-zero-annihilates",
  "contraction",
  "roundtrip",
  "equivalent",
  "associative",
  "commutative",
  "distributive",
  "idempotent",
  "identity",
  "distributes-over",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_algebra_law_of(const char *word, enum mt_algebra_law *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_algebra_law_names,
                            MT_VOCABULARY_COUNT(mt_algebra_law_names), word, &i) )
    return false;
  *member = (enum mt_algebra_law)i;
  return true;
}

/* (vocabulary answer-policy depth fair best-first) */
enum mt_answer_policy {
  MT_ANSWER_POLICY_DEPTH,
  MT_ANSWER_POLICY_FAIR,
  MT_ANSWER_POLICY_BEST_FIRST,
};

/* The engine's word for each enum mt_answer_policy member, by position. */
MT_VOCABULARY_TABLE char *const mt_answer_policy_names[] = {
  "depth",
  "fair",
  "best-first",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_answer_policy_of(const char *word, enum mt_answer_policy *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_answer_policy_names,
                            MT_VOCABULARY_COUNT(mt_answer_policy_names), word, &i) )
    return false;
  *member = (enum mt_answer_policy)i;
  return true;
}

/* (vocabulary applicability machine maybe prose) */
enum mt_applicability {
  MT_APPLICABILITY_MACHINE,
  MT_APPLICABILITY_MAYBE,
  MT_APPLICABILITY_PROSE,
};

/* The engine's word for each enum mt_applicability member, by position. */
MT_VOCABULARY_TABLE char *const mt_applicability_names[] = {
  "machine",
  "maybe",
  "prose",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_applicability_of(const char *word, enum mt_applicability *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_applicability_names,
                            MT_VOCABULARY_COUNT(mt_applicability_names), word, &i) )
    return false;
  *member = (enum mt_applicability)i;
  return true;
}

/* (vocabulary argument-delivery atoms values) */
enum mt_argument_delivery {
  MT_ARGUMENT_DELIVERY_ATOMS,
  MT_ARGUMENT_DELIVERY_VALUES,
};

/* The engine's word for each enum mt_argument_delivery member, by position. */
MT_VOCABULARY_TABLE char *const mt_argument_delivery_names[] = {
  "atoms",
  "values",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_argument_delivery_of(const char *word, enum mt_argument_delivery *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_argument_delivery_names,
                            MT_VOCABULARY_COUNT(mt_argument_delivery_names), word, &i) )
    return false;
  *member = (enum mt_argument_delivery)i;
  return true;
}

/* (vocabulary atomicity transactional atomic-single best-effort) */
enum mt_atomicity {
  MT_ATOMICITY_TRANSACTIONAL,
  MT_ATOMICITY_ATOMIC_SINGLE,
  MT_ATOMICITY_BEST_EFFORT,
};

/* The engine's word for each enum mt_atomicity member, by position. */
MT_VOCABULARY_TABLE char *const mt_atomicity_names[] = {
  "transactional",
  "atomic-single",
  "best-effort",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_atomicity_of(const char *word, enum mt_atomicity *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_atomicity_names,
                            MT_VOCABULARY_COUNT(mt_atomicity_names), word, &i) )
    return false;
  *member = (enum mt_atomicity)i;
  return true;
}

/* (vocabulary cache-policy force refuse plain incremental monotonic lazy
   shared private subsumptive lattice max-answers subgoal-abstract answer-
   abstract) */
enum mt_cache_policy {
  MT_CACHE_POLICY_FORCE,
  MT_CACHE_POLICY_REFUSE,
  MT_CACHE_POLICY_PLAIN,
  MT_CACHE_POLICY_INCREMENTAL,
  MT_CACHE_POLICY_MONOTONIC,
  MT_CACHE_POLICY_LAZY,
  MT_CACHE_POLICY_SHARED,
  MT_CACHE_POLICY_PRIVATE,
  MT_CACHE_POLICY_SUBSUMPTIVE,
  MT_CACHE_POLICY_LATTICE,
  MT_CACHE_POLICY_MAX_ANSWERS,
  MT_CACHE_POLICY_SUBGOAL_ABSTRACT,
  MT_CACHE_POLICY_ANSWER_ABSTRACT,
};

/* The engine's word for each enum mt_cache_policy member, by position. */
MT_VOCABULARY_TABLE char *const mt_cache_policy_names[] = {
  "force",
  "refuse",
  "plain",
  "incremental",
  "monotonic",
  "lazy",
  "shared",
  "private",
  "subsumptive",
  "lattice",
  "max-answers",
  "subgoal-abstract",
  "answer-abstract",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_cache_policy_of(const char *word, enum mt_cache_policy *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_cache_policy_names,
                            MT_VOCABULARY_COUNT(mt_cache_policy_names), word, &i) )
    return false;
  *member = (enum mt_cache_policy)i;
  return true;
}

/* (vocabulary cost-class constant log linear linearithmic quadratic
   exponential) */
enum mt_cost_class {
  MT_COST_CLASS_CONSTANT,
  MT_COST_CLASS_LOG,
  MT_COST_CLASS_LINEAR,
  MT_COST_CLASS_LINEARITHMIC,
  MT_COST_CLASS_QUADRATIC,
  MT_COST_CLASS_EXPONENTIAL,
};

/* The engine's word for each enum mt_cost_class member, by position. */
MT_VOCABULARY_TABLE char *const mt_cost_class_names[] = {
  "constant",
  "log",
  "linear",
  "linearithmic",
  "quadratic",
  "exponential",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_cost_class_of(const char *word, enum mt_cost_class *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_cost_class_names,
                            MT_VOCABULARY_COUNT(mt_cost_class_names), word, &i) )
    return false;
  *member = (enum mt_cost_class)i;
  return true;
}

/* (vocabulary delivery at-most-once at-least-once per-write-exactly) */
enum mt_delivery {
  MT_DELIVERY_AT_MOST_ONCE,
  MT_DELIVERY_AT_LEAST_ONCE,
  MT_DELIVERY_PER_WRITE_EXACTLY,
};

/* The engine's word for each enum mt_delivery member, by position. */
MT_VOCABULARY_TABLE char *const mt_delivery_names[] = {
  "at-most-once",
  "at-least-once",
  "per-write-exactly",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_delivery_of(const char *word, enum mt_delivery *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_delivery_names,
                            MT_VOCABULARY_COUNT(mt_delivery_names), word, &i) )
    return false;
  *member = (enum mt_delivery)i;
  return true;
}

/* (vocabulary delta-kind add remove progress) */
enum mt_delta_kind {
  MT_DELTA_KIND_ADD,
  MT_DELTA_KIND_REMOVE,
  MT_DELTA_KIND_PROGRESS,
};

/* The engine's word for each enum mt_delta_kind member, by position. */
MT_VOCABULARY_TABLE char *const mt_delta_kind_names[] = {
  "add",
  "remove",
  "progress",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_delta_kind_of(const char *word, enum mt_delta_kind *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_delta_kind_names,
                            MT_VOCABULARY_COUNT(mt_delta_kind_names), word, &i) )
    return false;
  *member = (enum mt_delta_kind)i;
  return true;
}

/* (vocabulary determinism det semidet nondet) */
enum mt_determinism {
  MT_DETERMINISM_DET,
  MT_DETERMINISM_SEMIDET,
  MT_DETERMINISM_NONDET,
};

/* The engine's word for each enum mt_determinism member, by position. */
MT_VOCABULARY_TABLE char *const mt_determinism_names[] = {
  "det",
  "semidet",
  "nondet",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_determinism_of(const char *word, enum mt_determinism *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_determinism_names,
                            MT_VOCABULARY_COUNT(mt_determinism_names), word, &i) )
    return false;
  *member = (enum mt_determinism)i;
  return true;
}

/* (vocabulary effect-class pureStructural readOnlyLookup
   nondeterministicReadOnly writesState oracleIO) */
enum mt_effect_class {
  MT_EFFECT_CLASS_PURE_STRUCTURAL,
  MT_EFFECT_CLASS_READ_ONLY_LOOKUP,
  MT_EFFECT_CLASS_NONDETERMINISTIC_READ_ONLY,
  MT_EFFECT_CLASS_WRITES_STATE,
  MT_EFFECT_CLASS_ORACLE_IO,
};

/* The engine's word for each enum mt_effect_class member, by position. */
MT_VOCABULARY_TABLE char *const mt_effect_class_names[] = {
  "pureStructural",
  "readOnlyLookup",
  "nondeterministicReadOnly",
  "writesState",
  "oracleIO",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_effect_class_of(const char *word, enum mt_effect_class *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_effect_class_names,
                            MT_VOCABULARY_COUNT(mt_effect_class_names), word, &i) )
    return false;
  *member = (enum mt_effect_class)i;
  return true;
}

/* (vocabulary event-order ordered unordered) */
enum mt_event_order {
  MT_EVENT_ORDER_ORDERED,
  MT_EVENT_ORDER_UNORDERED,
};

/* The engine's word for each enum mt_event_order member, by position. */
MT_VOCABULARY_TABLE char *const mt_event_order_names[] = {
  "ordered",
  "unordered",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_event_order_of(const char *word, enum mt_event_order *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_event_order_names,
                            MT_VOCABULARY_COUNT(mt_event_order_names), word, &i) )
    return false;
  *member = (enum mt_event_order)i;
  return true;
}

/* (vocabulary fidelity Exact Partial Sound Refuse) */
enum mt_fidelity {
  MT_FIDELITY_EXACT,
  MT_FIDELITY_PARTIAL,
  MT_FIDELITY_SOUND,
  MT_FIDELITY_REFUSE,
};

/* The engine's word for each enum mt_fidelity member, by position. */
MT_VOCABULARY_TABLE char *const mt_fidelity_names[] = {
  "Exact",
  "Partial",
  "Sound",
  "Refuse",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_fidelity_of(const char *word, enum mt_fidelity *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_fidelity_names,
                            MT_VOCABULARY_COUNT(mt_fidelity_names), word, &i) )
    return false;
  *member = (enum mt_fidelity)i;
  return true;
}

/* (vocabulary ground-kind host-reference metta-law arbiter) */
enum mt_ground_kind {
  MT_GROUND_KIND_HOST_REFERENCE,
  MT_GROUND_KIND_METTA_LAW,
  MT_GROUND_KIND_ARBITER,
};

/* The engine's word for each enum mt_ground_kind member, by position. */
MT_VOCABULARY_TABLE char *const mt_ground_kind_names[] = {
  "host-reference",
  "metta-law",
  "arbiter",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_ground_kind_of(const char *word, enum mt_ground_kind *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_ground_kind_names,
                            MT_VOCABULARY_COUNT(mt_ground_kind_names), word, &i) )
    return false;
  *member = (enum mt_ground_kind)i;
  return true;
}

/* (vocabulary image-mode opaque transparent auto) */
enum mt_image_mode {
  MT_IMAGE_MODE_OPAQUE,
  MT_IMAGE_MODE_TRANSPARENT,
  MT_IMAGE_MODE_AUTO,
};

/* The engine's word for each enum mt_image_mode member, by position. */
MT_VOCABULARY_TABLE char *const mt_image_mode_names[] = {
  "opaque",
  "transparent",
  "auto",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_image_mode_of(const char *word, enum mt_image_mode *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_image_mode_names,
                            MT_VOCABULARY_COUNT(mt_image_mode_names), word, &i) )
    return false;
  *member = (enum mt_image_mode)i;
  return true;
}

/* (vocabulary journal-sync none flush close) */
enum mt_journal_sync {
  MT_JOURNAL_SYNC_NONE,
  MT_JOURNAL_SYNC_FLUSH,
  MT_JOURNAL_SYNC_CLOSE,
};

/* The engine's word for each enum mt_journal_sync member, by position. */
MT_VOCABULARY_TABLE char *const mt_journal_sync_names[] = {
  "none",
  "flush",
  "close",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_journal_sync_of(const char *word, enum mt_journal_sync *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_journal_sync_names,
                            MT_VOCABULARY_COUNT(mt_journal_sync_names), word, &i) )
    return false;
  *member = (enum mt_journal_sync)i;
  return true;
}

/* (vocabulary limit events memory inferences timeout stack) */
enum mt_limit {
  MT_LIMIT_EVENTS,
  MT_LIMIT_MEMORY,
  MT_LIMIT_INFERENCES,
  MT_LIMIT_TIMEOUT,
  MT_LIMIT_STACK,
};

/* The engine's word for each enum mt_limit member, by position. */
MT_VOCABULARY_TABLE char *const mt_limit_names[] = {
  "events",
  "memory",
  "inferences",
  "timeout",
  "stack",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_limit_of(const char *word, enum mt_limit *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_limit_names,
                            MT_VOCABULARY_COUNT(mt_limit_names), word, &i) )
    return false;
  *member = (enum mt_limit)i;
  return true;
}

/* (vocabulary live-strategy pattern heads tabled) */
enum mt_live_strategy {
  MT_LIVE_STRATEGY_PATTERN,
  MT_LIVE_STRATEGY_HEADS,
  MT_LIVE_STRATEGY_TABLED,
};

/* The engine's word for each enum mt_live_strategy member, by position. */
MT_VOCABULARY_TABLE char *const mt_live_strategy_names[] = {
  "pattern",
  "heads",
  "tabled",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_live_strategy_of(const char *word, enum mt_live_strategy *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_live_strategy_names,
                            MT_VOCABULARY_COUNT(mt_live_strategy_names), word, &i) )
    return false;
  *member = (enum mt_live_strategy)i;
  return true;
}

/* (vocabulary memo-aggregate none min max sum count) */
enum mt_memo_aggregate {
  MT_MEMO_AGGREGATE_NONE,
  MT_MEMO_AGGREGATE_MIN,
  MT_MEMO_AGGREGATE_MAX,
  MT_MEMO_AGGREGATE_SUM,
  MT_MEMO_AGGREGATE_COUNT,
};

/* The engine's word for each enum mt_memo_aggregate member, by position. */
MT_VOCABULARY_TABLE char *const mt_memo_aggregate_names[] = {
  "none",
  "min",
  "max",
  "sum",
  "count",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_memo_aggregate_of(const char *word, enum mt_memo_aggregate *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_memo_aggregate_names,
                            MT_VOCABULARY_COUNT(mt_memo_aggregate_names), word, &i) )
    return false;
  *member = (enum mt_memo_aggregate)i;
  return true;
}

/* (vocabulary memo-strategy wtinylfu lru) */
enum mt_memo_strategy {
  MT_MEMO_STRATEGY_WTINYLFU,
  MT_MEMO_STRATEGY_LRU,
};

/* The engine's word for each enum mt_memo_strategy member, by position. */
MT_VOCABULARY_TABLE char *const mt_memo_strategy_names[] = {
  "wtinylfu",
  "lru",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_memo_strategy_of(const char *word, enum mt_memo_strategy *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_memo_strategy_names,
                            MT_VOCABULARY_COUNT(mt_memo_strategy_names), word, &i) )
    return false;
  *member = (enum mt_memo_strategy)i;
  return true;
}

/* (vocabulary numeric-type Number BigInt) */
enum mt_numeric_type {
  MT_NUMERIC_TYPE_NUMBER,
  MT_NUMERIC_TYPE_BIG_INT,
};

/* The engine's word for each enum mt_numeric_type member, by position. */
MT_VOCABULARY_TABLE char *const mt_numeric_type_names[] = {
  "Number",
  "BigInt",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_numeric_type_of(const char *word, enum mt_numeric_type *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_numeric_type_names,
                            MT_VOCABULARY_COUNT(mt_numeric_type_names), word, &i) )
    return false;
  *member = (enum mt_numeric_type)i;
  return true;
}

/* (vocabulary on-error-mode keep empty abort) */
enum mt_on_error {
  MT_ON_ERROR_KEEP,
  MT_ON_ERROR_EMPTY,
  MT_ON_ERROR_ABORT,
};

/* The engine's word for each enum mt_on_error member, by position. */
MT_VOCABULARY_TABLE char *const mt_on_error_names[] = {
  "keep",
  "empty",
  "abort",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_on_error_of(const char *word, enum mt_on_error *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_on_error_names,
                            MT_VOCABULARY_COUNT(mt_on_error_names), word, &i) )
    return false;
  *member = (enum mt_on_error)i;
  return true;
}

/* (vocabulary op-kind det many async raw_det raw_many) */
enum mt_op_kind {
  MT_OP_KIND_DET,
  MT_OP_KIND_MANY,
  MT_OP_KIND_ASYNC,
  MT_OP_KIND_RAW_DET,
  MT_OP_KIND_RAW_MANY,
};

/* The engine's word for each enum mt_op_kind member, by position. */
MT_VOCABULARY_TABLE char *const mt_op_kind_names[] = {
  "det",
  "many",
  "async",
  "raw_det",
  "raw_many",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_op_kind_of(const char *word, enum mt_op_kind *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_op_kind_names,
                            MT_VOCABULARY_COUNT(mt_op_kind_names), word, &i) )
    return false;
  *member = (enum mt_op_kind)i;
  return true;
}

/* (vocabulary provider-capability match enumerate add add-many remove clear
   subscribe plan rules tokens add-token remove-token savepoint) The engine
   declares this vocabulary OPEN: a word registered through (add-atom &metta
   (vocabulary-member provider-capability <word>)) is a value too, and
   mt_provider_capability_of answers false for it, as for any word this enum
   does not hold. */
enum mt_provider_capability {
  MT_PROVIDER_CAPABILITY_MATCH,
  MT_PROVIDER_CAPABILITY_ENUMERATE,
  MT_PROVIDER_CAPABILITY_ADD,
  MT_PROVIDER_CAPABILITY_ADD_MANY,
  MT_PROVIDER_CAPABILITY_REMOVE,
  MT_PROVIDER_CAPABILITY_CLEAR,
  MT_PROVIDER_CAPABILITY_SUBSCRIBE,
  MT_PROVIDER_CAPABILITY_PLAN,
  MT_PROVIDER_CAPABILITY_RULES,
  MT_PROVIDER_CAPABILITY_TOKENS,
  MT_PROVIDER_CAPABILITY_ADD_TOKEN,
  MT_PROVIDER_CAPABILITY_REMOVE_TOKEN,
  MT_PROVIDER_CAPABILITY_SAVEPOINT,
};

/* The engine's word for each enum mt_provider_capability member, by position. */
MT_VOCABULARY_TABLE char *const mt_provider_capability_names[] = {
  "match",
  "enumerate",
  "add",
  "add-many",
  "remove",
  "clear",
  "subscribe",
  "plan",
  "rules",
  "tokens",
  "add-token",
  "remove-token",
  "savepoint",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_provider_capability_of(const char *word, enum mt_provider_capability *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_provider_capability_names,
                            MT_VOCABULARY_COUNT(mt_provider_capability_names), word, &i) )
    return false;
  *member = (enum mt_provider_capability)i;
  return true;
}

/* (vocabulary refinement Gt Ge Lt Le Interval MultipleOf MinLen MaxLen Len
   Predicate Unit Literal) */
enum mt_refinement {
  MT_REFINEMENT_GT,
  MT_REFINEMENT_GE,
  MT_REFINEMENT_LT,
  MT_REFINEMENT_LE,
  MT_REFINEMENT_INTERVAL,
  MT_REFINEMENT_MULTIPLE_OF,
  MT_REFINEMENT_MIN_LEN,
  MT_REFINEMENT_MAX_LEN,
  MT_REFINEMENT_LEN,
  MT_REFINEMENT_PREDICATE,
  MT_REFINEMENT_UNIT,
  MT_REFINEMENT_LITERAL,
};

/* The engine's word for each enum mt_refinement member, by position. */
MT_VOCABULARY_TABLE char *const mt_refinement_names[] = {
  "Gt",
  "Ge",
  "Lt",
  "Le",
  "Interval",
  "MultipleOf",
  "MinLen",
  "MaxLen",
  "Len",
  "Predicate",
  "Unit",
  "Literal",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_refinement_of(const char *word, enum mt_refinement *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_refinement_names,
                            MT_VOCABULARY_COUNT(mt_refinement_names), word, &i) )
    return false;
  *member = (enum mt_refinement)i;
  return true;
}

/* (vocabulary refusal-kind syntax time_limit inference_limit restraint
   interrupted value type assertion capability platform operation stack
   source engine) */
enum mt_refusal_kind {
  MT_REFUSAL_KIND_SYNTAX,
  MT_REFUSAL_KIND_TIME_LIMIT,
  MT_REFUSAL_KIND_INFERENCE_LIMIT,
  MT_REFUSAL_KIND_RESTRAINT,
  MT_REFUSAL_KIND_INTERRUPTED,
  MT_REFUSAL_KIND_VALUE,
  MT_REFUSAL_KIND_TYPE,
  MT_REFUSAL_KIND_ASSERTION,
  MT_REFUSAL_KIND_CAPABILITY,
  MT_REFUSAL_KIND_PLATFORM,
  MT_REFUSAL_KIND_OPERATION,
  MT_REFUSAL_KIND_STACK,
  MT_REFUSAL_KIND_SOURCE,
  MT_REFUSAL_KIND_ENGINE,
};

/* The engine's word for each enum mt_refusal_kind member, by position. */
MT_VOCABULARY_TABLE char *const mt_refusal_kind_names[] = {
  "syntax",
  "time_limit",
  "inference_limit",
  "restraint",
  "interrupted",
  "value",
  "type",
  "assertion",
  "capability",
  "platform",
  "operation",
  "stack",
  "source",
  "engine",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_refusal_kind_of(const char *word, enum mt_refusal_kind *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_refusal_kind_names,
                            MT_VOCABULARY_COUNT(mt_refusal_kind_names), word, &i) )
    return false;
  *member = (enum mt_refusal_kind)i;
  return true;
}

/* (vocabulary registry-image expression symbol handle operations) */
enum mt_registry_image {
  MT_REGISTRY_IMAGE_EXPRESSION,
  MT_REGISTRY_IMAGE_SYMBOL,
  MT_REGISTRY_IMAGE_HANDLE,
  MT_REGISTRY_IMAGE_OPERATIONS,
};

/* The engine's word for each enum mt_registry_image member, by position. */
MT_VOCABULARY_TABLE char *const mt_registry_image_names[] = {
  "expression",
  "symbol",
  "handle",
  "operations",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_registry_image_of(const char *word, enum mt_registry_image *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_registry_image_names,
                            MT_VOCABULARY_COUNT(mt_registry_image_names), word, &i) )
    return false;
  *member = (enum mt_registry_image)i;
  return true;
}

/* (vocabulary remedy-kind quickfix refactor source) */
enum mt_remedy_kind {
  MT_REMEDY_KIND_QUICKFIX,
  MT_REMEDY_KIND_REFACTOR,
  MT_REMEDY_KIND_SOURCE,
};

/* The engine's word for each enum mt_remedy_kind member, by position. */
MT_VOCABULARY_TABLE char *const mt_remedy_kind_names[] = {
  "quickfix",
  "refactor",
  "source",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_remedy_kind_of(const char *word, enum mt_remedy_kind *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_remedy_kind_names,
                            MT_VOCABULARY_COUNT(mt_remedy_kind_names), word, &i) )
    return false;
  *member = (enum mt_remedy_kind)i;
  return true;
}

/* (vocabulary route-key context global) */
enum mt_route_key {
  MT_ROUTE_KEY_CONTEXT,
  MT_ROUTE_KEY_GLOBAL,
};

/* The engine's word for each enum mt_route_key member, by position. */
MT_VOCABULARY_TABLE char *const mt_route_key_names[] = {
  "context",
  "global",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_route_key_of(const char *word, enum mt_route_key *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_route_key_names,
                            MT_VOCABULARY_COUNT(mt_route_key_names), word, &i) )
    return false;
  *member = (enum mt_route_key)i;
  return true;
}

/* (vocabulary save-format metta fast) */
enum mt_save_format {
  MT_SAVE_FORMAT_METTA,
  MT_SAVE_FORMAT_FAST,
};

/* The engine's word for each enum mt_save_format member, by position. */
MT_VOCABULARY_TABLE char *const mt_save_format_names[] = {
  "metta",
  "fast",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_save_format_of(const char *word, enum mt_save_format *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_save_format_names,
                            MT_VOCABULARY_COUNT(mt_save_format_names), word, &i) )
    return false;
  *member = (enum mt_save_format)i;
  return true;
}

/* (vocabulary semiring bool visibility bag counting set ranked tropical prob
   prov budget formula polynomial amplitude) The engine declares this
   vocabulary OPEN: a word registered through (add-atom &metta (vocabulary-
   member semiring <word>)) is a value too, and mt_semiring_of answers false
   for it, as for any word this enum does not hold. */
enum mt_semiring {
  MT_SEMIRING_BOOL,
  MT_SEMIRING_VISIBILITY,
  MT_SEMIRING_BAG,
  MT_SEMIRING_COUNTING,
  MT_SEMIRING_SET,
  MT_SEMIRING_RANKED,
  MT_SEMIRING_TROPICAL,
  MT_SEMIRING_PROB,
  MT_SEMIRING_PROV,
  MT_SEMIRING_BUDGET,
  MT_SEMIRING_FORMULA,
  MT_SEMIRING_POLYNOMIAL,
  MT_SEMIRING_AMPLITUDE,
};

/* The engine's word for each enum mt_semiring member, by position. */
MT_VOCABULARY_TABLE char *const mt_semiring_names[] = {
  "bool",
  "visibility",
  "bag",
  "counting",
  "set",
  "ranked",
  "tropical",
  "prob",
  "prov",
  "budget",
  "formula",
  "polynomial",
  "amplitude",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_semiring_of(const char *word, enum mt_semiring *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_semiring_names,
                            MT_VOCABULARY_COUNT(mt_semiring_names), word, &i) )
    return false;
  *member = (enum mt_semiring)i;
  return true;
}

/* (vocabulary semiring-order ascending descending) */
enum mt_semiring_order {
  MT_SEMIRING_ORDER_ASCENDING,
  MT_SEMIRING_ORDER_DESCENDING,
};

/* The engine's word for each enum mt_semiring_order member, by position. */
MT_VOCABULARY_TABLE char *const mt_semiring_order_names[] = {
  "ascending",
  "descending",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_semiring_order_of(const char *word, enum mt_semiring_order *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_semiring_order_names,
                            MT_VOCABULARY_COUNT(mt_semiring_order_names), word, &i) )
    return false;
  *member = (enum mt_semiring_order)i;
  return true;
}

/* (vocabulary source-kind linear repeated peek) */
enum mt_source_kind {
  MT_SOURCE_KIND_LINEAR,
  MT_SOURCE_KIND_REPEATED,
  MT_SOURCE_KIND_PEEK,
};

/* The engine's word for each enum mt_source_kind member, by position. */
MT_VOCABULARY_TABLE char *const mt_source_kind_names[] = {
  "linear",
  "repeated",
  "peek",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_source_kind_of(const char *word, enum mt_source_kind *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_source_kind_names,
                            MT_VOCABULARY_COUNT(mt_source_kind_names), word, &i) )
    return false;
  *member = (enum mt_source_kind)i;
  return true;
}

/* (vocabulary space-capability file process network) */
enum mt_space_capability {
  MT_SPACE_CAPABILITY_FILE,
  MT_SPACE_CAPABILITY_PROCESS,
  MT_SPACE_CAPABILITY_NETWORK,
};

/* The engine's word for each enum mt_space_capability member, by position. */
MT_VOCABULARY_TABLE char *const mt_space_capability_names[] = {
  "file",
  "process",
  "network",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_space_capability_of(const char *word, enum mt_space_capability *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_space_capability_names,
                            MT_VOCABULARY_COUNT(mt_space_capability_names), word, &i) )
    return false;
  *member = (enum mt_space_capability)i;
  return true;
}

/* (vocabulary subscription-edge add remove both) */
enum mt_subscription_edge {
  MT_SUBSCRIPTION_EDGE_ADD,
  MT_SUBSCRIPTION_EDGE_REMOVE,
  MT_SUBSCRIPTION_EDGE_BOTH,
};

/* The engine's word for each enum mt_subscription_edge member, by position. */
MT_VOCABULARY_TABLE char *const mt_subscription_edge_names[] = {
  "add",
  "remove",
  "both",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_subscription_edge_of(const char *word, enum mt_subscription_edge *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_subscription_edge_names,
                            MT_VOCABULARY_COUNT(mt_subscription_edge_names), word, &i) )
    return false;
  *member = (enum mt_subscription_edge)i;
  return true;
}

/* (vocabulary visibility PUBLIC INTERNAL) */
enum mt_visibility {
  MT_VISIBILITY_PUBLIC,
  MT_VISIBILITY_INTERNAL,
};

/* The engine's word for each enum mt_visibility member, by position. */
MT_VOCABULARY_TABLE char *const mt_visibility_names[] = {
  "PUBLIC",
  "INTERNAL",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_visibility_of(const char *word, enum mt_visibility *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_visibility_names,
                            MT_VOCABULARY_COUNT(mt_visibility_names), word, &i) )
    return false;
  *member = (enum mt_visibility)i;
  return true;
}

/* (vocabulary volatility volatile stable immutable) */
enum mt_volatility {
  MT_VOLATILITY_VOLATILE,
  MT_VOLATILITY_STABLE,
  MT_VOLATILITY_IMMUTABLE,
};

/* The engine's word for each enum mt_volatility member, by position. */
MT_VOCABULARY_TABLE char *const mt_volatility_names[] = {
  "volatile",
  "stable",
  "immutable",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_volatility_of(const char *word, enum mt_volatility *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_volatility_names,
                            MT_VOCABULARY_COUNT(mt_volatility_names), word, &i) )
    return false;
  *member = (enum mt_volatility)i;
  return true;
}

/* (vocabulary wire-class term frame reply) */
enum mt_wire_class {
  MT_WIRE_CLASS_TERM,
  MT_WIRE_CLASS_FRAME,
  MT_WIRE_CLASS_REPLY,
};

/* The engine's word for each enum mt_wire_class member, by position. */
MT_VOCABULARY_TABLE char *const mt_wire_class_names[] = {
  "term",
  "frame",
  "reply",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_wire_class_of(const char *word, enum mt_wire_class *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_wire_class_names,
                            MT_VOCABULARY_COUNT(mt_wire_class_names), word, &i) )
    return false;
  *member = (enum mt_wire_class)i;
  return true;
}

/* (vocabulary wire-payload text number boolean term terms host handle truth
   bindings control) */
enum mt_wire_payload {
  MT_WIRE_PAYLOAD_TEXT,
  MT_WIRE_PAYLOAD_NUMBER,
  MT_WIRE_PAYLOAD_BOOLEAN,
  MT_WIRE_PAYLOAD_TERM,
  MT_WIRE_PAYLOAD_TERMS,
  MT_WIRE_PAYLOAD_HOST,
  MT_WIRE_PAYLOAD_HANDLE,
  MT_WIRE_PAYLOAD_TRUTH,
  MT_WIRE_PAYLOAD_BINDINGS,
  MT_WIRE_PAYLOAD_CONTROL,
};

/* The engine's word for each enum mt_wire_payload member, by position. */
MT_VOCABULARY_TABLE char *const mt_wire_payload_names[] = {
  "text",
  "number",
  "boolean",
  "term",
  "terms",
  "host",
  "handle",
  "truth",
  "bindings",
  "control",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_wire_payload_of(const char *word, enum mt_wire_payload *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_wire_payload_names,
                            MT_VOCABULARY_COUNT(mt_wire_payload_names), word, &i) )
    return false;
  *member = (enum mt_wire_payload)i;
  return true;
}

/* (vocabulary world closed-world open-world) */
enum mt_world {
  MT_WORLD_CLOSED_WORLD,
  MT_WORLD_OPEN_WORLD,
};

/* The engine's word for each enum mt_world member, by position. */
MT_VOCABULARY_TABLE char *const mt_world_names[] = {
  "closed-world",
  "open-world",
};

/* Whether word names a member, written to *member only when it does. */
static inline bool mt_world_of(const char *word, enum mt_world *member)
{ size_t i;
  if ( !mt_vocabulary_index(mt_world_names,
                            MT_VOCABULARY_COUNT(mt_world_names), word, &i) )
    return false;
  *member = (enum mt_world)i;
  return true;
}

/* Every vocabulary above, under the engine's own name for it. */
MT_VOCABULARY_TABLE mt_vocabulary mt_vocabularies[] = {
  { "ClauseFailedEnum", mt_clause_failed_enum_names,
    MT_VOCABULARY_COUNT(mt_clause_failed_enum_names) },
  { "EvaluationOrderEnum", mt_evaluation_order_enum_names,
    MT_VOCABULARY_COUNT(mt_evaluation_order_enum_names) },
  { "FunctionResultEnum", mt_function_result_enum_names,
    MT_VOCABULARY_COUNT(mt_function_result_enum_names) },
  { "MismatchEnum", mt_mismatch_enum_names,
    MT_VOCABULARY_COUNT(mt_mismatch_enum_names) },
  { "NoMatchEnum", mt_no_match_enum_names,
    MT_VOCABULARY_COUNT(mt_no_match_enum_names) },
  { "OutOfClausesEnum", mt_out_of_clauses_enum_names,
    MT_VOCABULARY_COUNT(mt_out_of_clauses_enum_names) },
  { "agenda-policy", mt_agenda_policy_names,
    MT_VOCABULARY_COUNT(mt_agenda_policy_names) },
  { "algebra-law", mt_algebra_law_names,
    MT_VOCABULARY_COUNT(mt_algebra_law_names) },
  { "answer-policy", mt_answer_policy_names,
    MT_VOCABULARY_COUNT(mt_answer_policy_names) },
  { "applicability", mt_applicability_names,
    MT_VOCABULARY_COUNT(mt_applicability_names) },
  { "argument-delivery", mt_argument_delivery_names,
    MT_VOCABULARY_COUNT(mt_argument_delivery_names) },
  { "atomicity", mt_atomicity_names,
    MT_VOCABULARY_COUNT(mt_atomicity_names) },
  { "cache-policy", mt_cache_policy_names,
    MT_VOCABULARY_COUNT(mt_cache_policy_names) },
  { "cost-class", mt_cost_class_names,
    MT_VOCABULARY_COUNT(mt_cost_class_names) },
  { "delivery", mt_delivery_names,
    MT_VOCABULARY_COUNT(mt_delivery_names) },
  { "delta-kind", mt_delta_kind_names,
    MT_VOCABULARY_COUNT(mt_delta_kind_names) },
  { "determinism", mt_determinism_names,
    MT_VOCABULARY_COUNT(mt_determinism_names) },
  { "effect-class", mt_effect_class_names,
    MT_VOCABULARY_COUNT(mt_effect_class_names) },
  { "event-order", mt_event_order_names,
    MT_VOCABULARY_COUNT(mt_event_order_names) },
  { "fidelity", mt_fidelity_names,
    MT_VOCABULARY_COUNT(mt_fidelity_names) },
  { "ground-kind", mt_ground_kind_names,
    MT_VOCABULARY_COUNT(mt_ground_kind_names) },
  { "image-mode", mt_image_mode_names,
    MT_VOCABULARY_COUNT(mt_image_mode_names) },
  { "journal-sync", mt_journal_sync_names,
    MT_VOCABULARY_COUNT(mt_journal_sync_names) },
  { "limit", mt_limit_names,
    MT_VOCABULARY_COUNT(mt_limit_names) },
  { "live-strategy", mt_live_strategy_names,
    MT_VOCABULARY_COUNT(mt_live_strategy_names) },
  { "memo-aggregate", mt_memo_aggregate_names,
    MT_VOCABULARY_COUNT(mt_memo_aggregate_names) },
  { "memo-strategy", mt_memo_strategy_names,
    MT_VOCABULARY_COUNT(mt_memo_strategy_names) },
  { "numeric-type", mt_numeric_type_names,
    MT_VOCABULARY_COUNT(mt_numeric_type_names) },
  { "on-error-mode", mt_on_error_names,
    MT_VOCABULARY_COUNT(mt_on_error_names) },
  { "op-kind", mt_op_kind_names,
    MT_VOCABULARY_COUNT(mt_op_kind_names) },
  { "provider-capability", mt_provider_capability_names,
    MT_VOCABULARY_COUNT(mt_provider_capability_names) },
  { "refinement", mt_refinement_names,
    MT_VOCABULARY_COUNT(mt_refinement_names) },
  { "refusal-kind", mt_refusal_kind_names,
    MT_VOCABULARY_COUNT(mt_refusal_kind_names) },
  { "registry-image", mt_registry_image_names,
    MT_VOCABULARY_COUNT(mt_registry_image_names) },
  { "remedy-kind", mt_remedy_kind_names,
    MT_VOCABULARY_COUNT(mt_remedy_kind_names) },
  { "route-key", mt_route_key_names,
    MT_VOCABULARY_COUNT(mt_route_key_names) },
  { "save-format", mt_save_format_names,
    MT_VOCABULARY_COUNT(mt_save_format_names) },
  { "semiring", mt_semiring_names,
    MT_VOCABULARY_COUNT(mt_semiring_names) },
  { "semiring-order", mt_semiring_order_names,
    MT_VOCABULARY_COUNT(mt_semiring_order_names) },
  { "source-kind", mt_source_kind_names,
    MT_VOCABULARY_COUNT(mt_source_kind_names) },
  { "space-capability", mt_space_capability_names,
    MT_VOCABULARY_COUNT(mt_space_capability_names) },
  { "subscription-edge", mt_subscription_edge_names,
    MT_VOCABULARY_COUNT(mt_subscription_edge_names) },
  { "visibility", mt_visibility_names,
    MT_VOCABULARY_COUNT(mt_visibility_names) },
  { "volatility", mt_volatility_names,
    MT_VOCABULARY_COUNT(mt_volatility_names) },
  { "wire-class", mt_wire_class_names,
    MT_VOCABULARY_COUNT(mt_wire_class_names) },
  { "wire-payload", mt_wire_payload_names,
    MT_VOCABULARY_COUNT(mt_wire_payload_names) },
  { "world", mt_world_names,
    MT_VOCABULARY_COUNT(mt_world_names) },
};

#endif
